version: '3.1'

services:
  db:
    image: postgres:10
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - financeiro:/var/lib/postgresql

volumes:
  financeiro: